package com.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCash<M extends BaseCash<M>> extends Model<M> implements IBean {

	public void setCashId(java.lang.Integer cashId) {
		set("cash_id", cashId);
	}

	public java.lang.Integer getCashId() {
		return get("cash_id");
	}

	public void setCashName(java.lang.String cashName) {
		set("cash_name", cashName);
	}

	public java.lang.String getCashName() {
		return get("cash_name");
	}

	public void setCashDo(java.lang.String cashDo) {
		set("cash_do", cashDo);
	}

	public java.lang.String getCashDo() {
		return get("cash_do");
	}

	public void setCashFlag(java.lang.Integer cashFlag) {
		set("cash_flag", cashFlag);
	}

	public java.lang.Integer getCashFlag() {
		return get("cash_flag");
	}

}
