package com.shop.model;

import java.util.List;

import com.shop.model.base.BaseCash;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cash extends BaseCash<Cash> {
	public static final Cash dao = new Cash();
	
	/**
	 * 获取销售方式
	 * @return
	 */
	public List<Cash> getCash() {
		List<Cash> cashs = dao.find("select * from shop_cash where cash_flag != 1");
		return cashs;
	}
}
